# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Alura Ingressos' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Alura Ingressos
  pod 'CPF-CNPJ-Validator'
#  pod 'AFNetworking', '~> 3.0'
  pod 'Alamofire', '~> 5.0.0-rc.3'
  pod "CreditCardValidator", '~> 0.4'
  pod 'Money', '~> 2.0'
  
end
